import Details from '@theme/Details';
import React from 'react';

type ConstantsDropdownVariant =
  | 'CHAIN'
  | 'CHAIN_FULL'
  | 'PUSH_NETWORK'
  | 'LIBRARY'
  | 'MOVEABLE_TOKEN'
  | 'PAYABLE_TOKEN';

interface ConstantsDropdownProps {
  variant: ConstantsDropdownVariant;
}

const CONSTANTS_MAP: Record<
  ConstantsDropdownVariant,
  { summary: string; values: string[] }
> = {
  CHAIN: {
    summary: 'PushChain.CONSTANTS.CHAIN',
    values: [
      'PushChain.CONSTANTS.CHAIN.PUSH_TESTNET',
      'PushChain.CONSTANTS.CHAIN.PUSH_TESTNET_DONUT',
      'PushChain.CONSTANTS.CHAIN.ETHEREUM_SEPOLIA',
      'PushChain.CONSTANTS.CHAIN.BNB_TESTNET',
      'PushChain.CONSTANTS.CHAIN.BASE_SEPOLIA',
      'PushChain.CONSTANTS.CHAIN.ARBITRUM_SEPOLIA',
      'PushChain.CONSTANTS.CHAIN.SOLANA_DEVNET',
    ],
  },
  CHAIN_FULL: {
    summary: 'PushChain.CONSTANTS.CHAIN',
    values: [
      'PushChain.CONSTANTS.CHAIN.PUSH_MAINNET',
      'PushChain.CONSTANTS.CHAIN.PUSH_TESTNET',
      'PushChain.CONSTANTS.CHAIN.PUSH_TESTNET_DONUT',
      'PushChain.CONSTANTS.CHAIN.PUSH_LOCALNET',
      'PushChain.CONSTANTS.CHAIN.ETHEREUM_MAINNET',
      'PushChain.CONSTANTS.CHAIN.ETHEREUM_SEPOLIA',
      'PushChain.CONSTANTS.CHAIN.SOLANA_MAINNET',
      'PushChain.CONSTANTS.CHAIN.SOLANA_TESTNET',
      'PushChain.CONSTANTS.CHAIN.SOLANA_DEVNET',
    ],
  },
  PUSH_NETWORK: {
    summary: 'PushChain.CONSTANTS.PUSH_NETWORK',
    values: [
      'PushChain.CONSTANTS.PUSH_NETWORK.TESTNET',
      'PushChain.CONSTANTS.PUSH_NETWORK.LOCALNET',
    ],
  },
  LIBRARY: {
    summary: 'PushChain.CONSTANTS.LIBRARY',
    values: [
      'PushChain.CONSTANTS.LIBRARY.ETHEREUM_ETHERSV6',
      'PushChain.CONSTANTS.LIBRARY.ETHEREUM_VIEM',
      'PushChain.CONSTANTS.LIBRARY.SOLANA_WEB3JS',
    ],
  },
  MOVEABLE_TOKEN: {
    summary: 'PushChain.CONSTANTS.MOVEABLE.TOKEN',
    values: [
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.ETHEREUM_SEPOLIA.ETH',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.ETHEREUM_SEPOLIA.USDT',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.ETHEREUM_SEPOLIA.USDC',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.ETHEREUM_SEPOLIA.WETH',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.ETHEREUM_SEPOLIA.stETH',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.ARBITRUM_SEPOLIA.ETH',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.ARBITRUM_SEPOLIA.USDT',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.ARBITRUM_SEPOLIA.USDC',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.ARBITRUM_SEPOLIA.WETH',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.BASE_SEPOLIA.ETH',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.BASE_SEPOLIA.USDT',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.BASE_SEPOLIA.USDC',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.BASE_SEPOLIA.WETH',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.BNB_TESTNET.BNB',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.BNB_TESTNET.USDT',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.BNB_TESTNET.USDC',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.SOLANA_DEVNET.SOL',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.SOLANA_DEVNET.USDT',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.SOLANA_DEVNET.USDC',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.pEth',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.pEthArb',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.pEthBase',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.pBnb',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.pSol',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.USDT.eth',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.USDT.arb',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.USDT.base',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.USDT.bnb',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.USDT.sol',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.USDC.eth',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.USDC.arb',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.USDC.base',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.USDC.bsc',
      'PushChain.CONSTANTS.MOVEABLE.TOKEN.PUSH_TESTNET_DONUT.USDC.sol',
    ],
  },
  PAYABLE_TOKEN: {
    summary: 'PushChain.CONSTANTS.PAYABLE.TOKEN',
    values: [
      'PushChain.CONSTANTS.PAYABLE.TOKEN.ETHEREUM_SEPOLIA.ETH',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.ETHEREUM_SEPOLIA.USDT',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.ETHEREUM_SEPOLIA.USDC',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.ETHEREUM_SEPOLIA.WETH',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.ETHEREUM_SEPOLIA.stETH',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.ARBITRUM_SEPOLIA.ETH',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.ARBITRUM_SEPOLIA.USDT',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.ARBITRUM_SEPOLIA.USDC',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.BASE_SEPOLIA.ETH',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.BASE_SEPOLIA.USDT',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.BASE_SEPOLIA.USDC',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.BNB_TESTNET.BNB',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.BNB_TESTNET.USDT',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.BNB_TESTNET.USDC',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.SOLANA_DEVNET.SOL',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.SOLANA_DEVNET.USDT',
      'PushChain.CONSTANTS.PAYABLE.TOKEN.SOLANA_DEVNET.USDC',
    ],
  },
};

export default function ConstantsDropdown({ variant }: ConstantsDropdownProps) {
  const { summary, values } = CONSTANTS_MAP[variant];
  return (
    <Details
      summary={<summary>{summary}</summary>}
      className='alert alert--minimal-api-table'
    >
      <div style={{ paddingTop: '8px' }}>
        {values.map((v) => (
          <code key={v}>{v}</code>
        ))}
      </div>
    </Details>
  );
}
