/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  pushChainSidebar: [
    {
      type: 'doc',
      id: 'chain/introduction',
    },
    {
      type: 'doc',
      id: 'chain/docs-chain-quickstart',
    },
    {
      type: 'doc',
      id: 'chain/docs-chain-important-concepts',
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'doc',
        id: 'chain/docs-chain-tutorials-section',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Basics',
          link: {
            type: 'doc',
            id: 'chain/tutorials/docs-chain-tutorial-basics-section',
          },
          collapsed: true,
          items: [
            { type: 'autogenerated', dirName: 'chain/01-tutorials/01-basics' },
          ],
        },
        {
          type: 'category',
          label: 'Power Features',
          link: {
            type: 'doc',
            id: 'chain/tutorials/docs-chain-tutorial-power-features-section',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'chain/01-tutorials/02-power-features',
            },
          ],
        },
        // {
        //   type: 'category',
        //   label: 'Tokens and Airdrops',
        //   link: {
        //     type: 'doc',
        //     id: 'chain/tutorials/docs-chain-tutorial-tokens-and-airdrops-section',
        //   },
        //   collapsed: true,
        //   items: [
        //     {
        //       type: 'autogenerated',
        //       dirName: 'chain/01-tutorials/02-tokens-and-airdrops',
        //     },
        //   ],
        // },
        // {
        //   type: 'category',
        //   label: 'Payments and DeFi',
        //   link: {
        //     type: 'doc',
        //     id: 'chain/tutorials/docs-chain-tutorial-payments-and-defi-section',
        //   },
        //   collapsed: true,
        //   items: [
        //     {
        //       type: 'autogenerated',
        //       dirName: 'chain/01-tutorials/03-payments-and-defi',
        //     },
        //   ],
        // },
        {
          type: 'category',
          label: 'Integration and Tooling',
          link: {
            type: 'doc',
            id: 'chain/tutorials/docs-chain-tutorial-integration-and-tooling-section',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'chain/01-tutorials/04-integration-and-tooling',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Setup',
      link: {
        type: 'doc',
        id: 'chain/docs-chain-setup-section',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Tooling',
          link: {
            type: 'doc',
            id: 'chain/setup/docs-chain-setup-tooling-section',
          },
          collapsed: true,
          items: [
            { type: 'autogenerated', dirName: 'chain/02-setup/01-tooling' },
          ],
        },
        {
          type: 'category',
          label: 'Smart Contract Environment',
          link: {
            type: 'doc',
            id: 'chain/setup/docs-chain-setup-smart-contract-environment-section',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'chain/02-setup/02-smart-contract-environment',
            },
          ],
        },
        {
          type: 'doc',
          id: 'chain/setup/docs-chain-setup-chain-config',
        },
      ],
    },
    {
      type: 'category',
      label: 'Build',
      link: {
        type: 'doc',
        id: 'chain/docs-chain-build-section',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'chain/build/docs-chain-build-recommended-practices',
        },
        {
          type: 'doc',
          id: 'chain/build/docs-chain-build-create-universal-signer',
        },
        {
          type: 'doc',
          id: 'chain/build/docs-chain-build-push-chain-client',
        },
        {
          type: 'doc',
          id: 'chain/build/docs-chain-build-initialize-evm-client',
        },
        {
          type: 'doc',
          id: 'chain/build/docs-chain-build-send-universal-transaction',
        },
        {
          type: 'doc',
          id: 'chain/build/docs-chain-build-sign-universal-message',
        },
        {
          type: 'doc',
          id: 'chain/build/docs-chain-build-utility-functions',
        },
        {
          type: 'doc',
          id: 'chain/build/docs-chain-build-reading-blockchain-state',
        },
        {
          type: 'doc',
          id: 'chain/build/docs-chain-build-contract-helpers',
        },
        {
          type: 'category',
          label: 'Advanced',
          link: {
            type: 'doc',
            id: 'chain/build/docs-chain-build-advanced-section',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'chain/03-build/01-advanced',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'UI Kit',
      link: {
        type: 'doc',
        id: 'chain/docs-chain-ui-kit-section',
      },
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'chain/ui-kit/docs-chain-ui-components-integrate-push-universal-wallet',
        },
        {
          type: 'category',
          label: 'Customizations',
          link: {
            type: 'doc',
            id: 'chain/ui-kit/docs-chain-ui-kit-customizations-section',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'chain/04-ui-kit/01-customizations',
            },
          ],
        },
        {
          type: 'category',
          label: 'Examples',
          link: {
            type: 'doc',
            id: 'chain/ui-kit/docs-chain-ui-kit-examples-section',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'chain/04-ui-kit/02-examples',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deep Dives',
      link: {
        type: 'doc',
        id: 'chain/docs-chain-deep-dives-section',
      },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'chain/05-deep-dives' }],
    },
    {
      type: 'category',
      label: 'Node & System Tools',
      link: {
        type: 'doc',
        id: 'chain/docs-chain-node-and-system-tools-section',
      },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'chain/06-node-and-system-tools' },
      ],
    },
    {
      type: 'link',
      label: 'Knowledge Base',
      href: 'https://push.org/knowledge',
    },
    {
      type: 'doc',
      id: 'chain/docs-chain-changelog',
    },
  ],
};

module.exports = sidebars;
