import { EcosystemApp } from '@site/src/components/Ecosystem/EcosystemBlocks';

export const EcosystemFeaturedListUrls = [
  'https://pusd.push.org/',
  'https://zappi.to/',
  'https://ramenfi.xyz/',
  'https://degenchess.fun/',
  'https://cetra.app/',
  'https://www.thehodl.fun/',
  'https://push-ninja.fun',
  'https://eon-five.vercel.app',
  'https://www.halofy.ai/',
  'https://catkevin.github.io/OnchainVampireSurvivors/',
  'https://www.lastone.fun/',
] as const;

export const EcosystemPartnersList: EcosystemApp[] = [
  {
    nameKey: 'components.ecosystem-apps-partners.partners.silence-labs.name',
    descriptionKey:
      'components.ecosystem-apps-partners.partners.silence-labs.description',
    icon: '/assets/ecosystem/silencelabs-icon.png',
    bgImage: '/assets/ecosystem/silencelabs-bg.png',
    bgGradientColor: '#000000',
    tags: ['Partners'],
    twitterId: '2016511466199990733',
    href: 'https://silencelaboratories.com/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.partners.human-tech.name',
    descriptionKey:
      'components.ecosystem-apps-partners.partners.human-tech.description',
    icon: '/assets/ecosystem/humantech-icon.png',
    bgImage: '/assets/ecosystem/humantech-bg.png',
    bgGradientColor: '#201D28',
    tags: ['Partners'],
    href: 'https://human.tech/',
    titleColor: 'white',
  },
];

export const EcosystemAppsList: EcosystemApp[] = [
  {
    nameKey: 'components.ecosystem-apps-partners.apps.pusd.name',
    descriptionKey: 'components.ecosystem-apps-partners.apps.pusd.description',
    icon: '/assets/ecosystem/pusd-icon.png',
    bgImage: '/assets/ecosystem/pusd-bg.png',
    bgGradientColor: '#371243',
    tags: ['DeFi'],
    href: 'https://pusd.push.org/',
    titleColor: 'white',
    descriptionColor: 'white',
    twitterId: '1993681001076478131',
    tagsColor: 'white',
  },
  {
    nameKey: 'Zappi.to',
    descriptionKey:
      'Your crypto, your rules: seamless payments across every chain.',
    icon: '/assets/ecosystem/zappi-to-icon.png',
    bgImage: '/assets/ecosystem/zappi-to-bg.png',
    bgGradientColor: '#4A13BB',
    tags: ['Payments'],
    href: 'https://zappi.to/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.ramen-swap.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.ramen-swap.description',
    icon: '/assets/ecosystem/ramenfi-icon.png',
    bgImage: '/assets/ecosystem/ramenfi-bg.png',
    bgGradientColor: '#DB2D33',
    tags: ['DeFi'],
    href: 'https://ramenfi.xyz/',
    titleColor: 'white',
    descriptionColor: 'white',
    tagsColor: 'white',
    appoftheweek: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.degen-chess.name',
    descriptionKey:
      'Play, wage bets, stream and guess the winner to win the pool',
    icon: '/assets/ecosystem/degen-chess-icon.png',
    bgImage: '/assets/ecosystem/degen-chess-bg.png',
    bgGradientColor: '#4F38A8',
    tags: ['Gaming/Streaming'],
    href: 'https://degenchess.fun/',
    titleColor: 'white',
    descriptionColor: 'white',
    tagsColor: 'white',
    twitterId: '2031754422884487425',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.cetra.name',
    descriptionKey: 'components.ecosystem-apps-partners.apps.cetra.description',
    icon: '/assets/ecosystem/cetra-icon.png',
    bgImage: '/assets/ecosystem/cetra-bg.png',
    bgGradientColor: '#000000',
    tags: ['DeFi'],
    href: 'https://cetra.app/',
    titleColor: 'white',
    descriptionColor: 'white',
    tagsColor: 'white',
    twitterId: '2029168701916774742',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.hodl-fun.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.hodl-fun.description',
    icon: '/assets/ecosystem/hodl-fun-icon.png',
    bgImage: '/assets/ecosystem/hodl-fun-bg.png',
    bgGradientColor: 'rgba(0, 0, 0, 0.80)',
    tags: ['DeFi'],
    twitterId: '1989664475784663041',
    href: 'https://www.thehodl.fun/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.push-ninja.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.push-ninja.description',
    icon: '/assets/ecosystem/push-ninja-icon.png',
    bgImage: '/assets/ecosystem/push-ninja-bg.png',
    bgGradientColor: '#5D1D51',
    tags: ['Gaming'],
    twitterId: '2014018188434964672',
    href: 'https://push-ninja.fun',
    titleColor: 'white',
    spotlighttextKey:
      'components.ecosystem-apps-partners.apps.push-ninja.spotlight-text',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.eon-ai-butler.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.eon-ai-butler.description',
    icon: '/assets/ecosystem/eon-icon.png',
    bgImage: '/assets/ecosystem/eon-bg.png',
    bgGradientColor: '#000000',
    tags: ['Agentic AI'],
    twitterId: '1989664469484728745',
    href: 'https://eon-five.vercel.app',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.halo.name',
    descriptionKey: 'components.ecosystem-apps-partners.apps.halo.description',
    icon: '/assets/ecosystem/halo-icon.png',
    bgImage: '/assets/ecosystem/halo-bg.png',
    bgGradientColor: '#F3F6EC',
    tags: ['Agentic AI'],
    href: 'https://www.halofy.ai/',
    titleColor: 'black',
    descriptionColor: 'black',
    tagsColor: 'black',
  },
  {
    nameKey:
      'components.ecosystem-apps-partners.apps.onchain-vampire-survivors.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.onchain-vampire-survivors.description',
    icon: '/assets/ecosystem/onchain-vampires-icon.png',
    bgImage: '/assets/ecosystem/onchain-vampires-bg.png',
    bgGradientColor: '#5D261E',
    tags: ['Gaming'],
    twitterId: '2003875166850531341',
    href: 'https://catkevin.github.io/OnchainVampireSurvivors/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.last-one.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.last-one.description',
    icon: '/assets/ecosystem/last-one-icon.png',
    bgImage: '/assets/ecosystem/last-one-bg.png',
    bgGradientColor: '#E5B92A',
    tags: ['Gaming'],
    href: 'https://www.lastone.fun/',
    titleColor: 'black',
    descriptionColor: 'black',
    twitterId: '1993681001076478131',
    tagsColor: 'black',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.puffles.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.puffles.description',
    icon: '/assets/ecosystem/puffles-icon.jpg',
    bgImage: '/assets/ecosystem/puffles-bg.jpg',
    bgGradientColor: '#000000',
    tags: ['NFT'],
    href: 'https://puffles.io',
    titleColor: 'white',
    descriptionColor: 'white',
    tagsColor: 'white',
    twitterId: '2031754422884487425',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.pns.name',
    descriptionKey: 'components.ecosystem-apps-partners.apps.pns.description',
    icon: '/assets/ecosystem/pns-icon.png',
    bgImage: '/assets/ecosystem/pns-bg.png',
    bgGradientColor: '#4A1756',
    tags: ['Infra'],
    twitterId: '1989664489902575819',
    href: 'https://universal-name-service.vercel.app/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.push-x402.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.push-x402.description',
    icon: '/assets/ecosystem/push402-icon.png',
    bgImage: '/assets/ecosystem/push402-bg.png',
    bgGradientColor: '#010101',
    tags: ['Infra'],
    href: 'https://pushindexer.vercel.app',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.bountive.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.bountive.description',
    icon: '/assets/ecosystem/bountive-icon.png',
    bgImage: '/assets/ecosystem/bountive-bg.png',
    bgGradientColor: '#000000',
    tags: ['Crowdfunding'],
    twitterId: '1989664498920403443',
    href: 'https://bountive.vercel.app/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.beat-brawls.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.beat-brawls.description',
    icon: '/assets/ecosystem/beatbrawls-icon.png',
    bgImage: '/assets/ecosystem/beatbrawls-bg.png',
    bgGradientColor: '#301139',
    tags: ['Gaming'],
    href: 'https://push.beatbrawls.com/',
    titleColor: 'white',
    twitterId: '2001278428788715678',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.apt-casino.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.apt-casino.description',
    icon: '/assets/ecosystem/apt-casino-icon.png',
    bgImage: '/assets/ecosystem/apt-casino-bg.png',
    bgGradientColor: '#5E1140',
    tags: ['Gaming'],
    twitterId: '1989664509439713780',
    href: 'https://apt-casino-push-chain.vercel.app/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.tip-up.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.tip-up.description',
    icon: '/assets/ecosystem/tip-up-icon.png',
    bgImage: '/assets/ecosystem/tip-up-bg.png',
    bgGradientColor: '#000000',
    tags: ['DeFi'],
    twitterId: '1989664514686783920',
    href: 'https://tip-up-push.vercel.app/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.push-swap.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.push-swap.description',
    icon: '/assets/ecosystem/push-swap-icon.png',
    bgImage: '/assets/ecosystem/push-swap-bg.png',
    bgGradientColor: '#DD60C4',
    tags: ['DeFi'],
    twitterId: '1989664440468590639',
    href: 'https://push-swap-sepia.vercel.app/',
    titleColor: 'black',
    descriptionColor: 'black',
    tagsColor: 'black',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.chain-circle.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.chain-circle.description',
    icon: '/assets/ecosystem/chaincircle-icon.png',
    bgImage: '/assets/ecosystem/chaincircle-bg.png',
    bgGradientColor: '#000000',
    tags: ['DeFi'],
    twitterId: '1989664436433637415',
    href: 'https://www.chaincircle.org/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.push-campus.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.push-campus.description',
    icon: '/assets/ecosystem/push-campus-icon.png',
    bgImage: '/assets/ecosystem/push-campus-bg.png',
    bgGradientColor: '#000000',
    tags: ['Social'],
    twitterId: '1989664494503743894',
    href: 'https://push-campus.vercel.app/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.ballsy.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.ballsy.description',
    icon: '/assets/ecosystem/ballsy-icon.png',
    bgImage: '/assets/ecosystem/ballsy-bg.png',
    bgGradientColor: 'rgba(0, 0, 0, 0.80)',
    tags: ['Gaming'],
    href: 'https://ballsy.push.org/',
    titleColor: 'white',
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.freename.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.freename.description',
    icon: '/assets/ecosystem/freename-icon.png',
    bgImage: '/assets/ecosystem/freename-bg.png',
    bgGradientColor: '#030303',
    tags: ['Infra'],
    href: 'https://omnihub.xyz/discover/push-testnet',
    titleColor: '#FFFFFF',
    comingsoon: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.hang4-fun.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.hang4-fun.description',
    icon: '/assets/ecosystem/hangfun-icon.png',
    bgImage: '/assets/ecosystem/hangfun-bg.png',
    bgGradientColor: 'rgba(148, 163, 184, 0.25)',
    tags: ['TBA'],
    href: 'https://hang4.fun/',
    titleColor: 'white',
    comingsoon: true,
  },
  // Doesn't work so disabled
  // {
  //   name: 'Athera',
  //   description: 'Automated crypto inheritance',
  //   icon: '/assets/ecosystem/athera-icon.png',
  //   bgImage: '/assets/ecosystem/athera-bg.png',
  //   bgGradientColor: '#000000',
  //   tags: ['DeFi'],
  //   twitterId: '1989664503341129977',
  //   href: 'https://atherra.vercel.app/',
  //   titleColor: 'white',
  // },
  // --- Secondary (smaller grid) ---
  {
    nameKey: 'components.ecosystem-apps-partners.apps.omnihub.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.omnihub.description',
    icon: '/assets/ecosystem/omnihub-icon.png',
    bgImage: '/assets/ecosystem/omnihub-bg.png',
    bgGradientColor: '#030303',
    tags: ['NFT'],
    href: 'https://omnihub.xyz/discover/push-testnet',
    titleColor: '#FFFFFF',
    secondary: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.push-dex.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.push-dex.description',
    icon: '/assets/ecosystem/pushdex-icon.png',
    bgImage: '/assets/ecosystem/pushdex-bg.png',
    bgGradientColor: '#030303',
    tags: ['DeFi'],
    href: 'https://pushdex.lovable.app/',
    titleColor: '#FFFFFF',
    twitterId: '2011506398597955757',
    secondary: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.zns.name',
    descriptionKey: 'components.ecosystem-apps-partners.apps.zns.description',
    icon: '/assets/ecosystem/zns-icon.png',
    bgImage: '/assets/ecosystem/zns-bg.png',
    bgGradientColor: '#A9D20A',
    tags: ['Infra'],
    href: 'https://zns.bio/gm-deploy?filter=all&tab=gm&search=push',
    titleColor: 'black',
    descriptionColor: 'black',
    tagsColor: 'black',
    twitterId: '1998756795859550371',
    secondary: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.star-run.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.star-run.description',
    icon: '/assets/ecosystem/star-run-icon.png',
    bgImage: '/assets/ecosystem/star-run-bg.png',
    bgGradientColor: '#000000',
    tags: ['Gaming'],
    twitterId: '1989664445501751672',
    href: 'https://starrun.vercel.app/',
    titleColor: 'white',
    secondary: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.forge-realm.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.forge-realm.description',
    icon: '/assets/ecosystem/forge-realm-icon.png',
    bgImage: '/assets/ecosystem/forge-realm-bg.png',
    bgGradientColor: '#000000',
    tags: ['NFT'],
    twitterId: '1989664480616464799',
    href: 'https://forge-realm.vercel.app/',
    titleColor: 'white',
    secondary: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.conft-codomain.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.conft-codomain.description',
    icon: '/assets/ecosystem/conft-icon.png',
    bgImage: '/assets/ecosystem/conft-bg.png',
    bgGradientColor: '#000',
    tags: ['NFT'],
    href: 'https://conft.app/?chainId=42101',
    titleColor: 'white',
    secondary: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.copet.name',
    descriptionKey: 'components.ecosystem-apps-partners.apps.copet.description',
    icon: '/assets/ecosystem/copet-icon.png',
    bgImage: '/assets/ecosystem/copet-bg.png',
    bgGradientColor: '#010101',
    tags: ['NFT'],
    href: 'https://copet.xyz/?chainId=42101',
    titleColor: '#FFFFFF',
    secondary: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.surf-layer.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.surf-layer.description',
    icon: '/assets/ecosystem/surflayer-icon.png',
    bgImage: '/assets/ecosystem/surflayer-bg.png',
    bgGradientColor: '#030303',
    tags: ['DeFi'],
    href: 'https://surflayer.xyz/',
    titleColor: '#FFFFFF',
    secondary: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.push-name-service.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.push-name-service.description',
    icon: '/assets/ecosystem/push-name-service-icon.png',
    bgImage: '/assets/ecosystem/push-name-service-bg.png',
    bgGradientColor: '#000000',
    tags: ['Infra'],
    twitterId: '1989664485427351900',
    href: 'https://push-name-service.vercel.app/',
    titleColor: 'white',
    secondary: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.nfts2me.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.nfts2me.description',
    icon: '/assets/ecosystem/nfts-me-icon.png',
    bgImage: '/assets/ecosystem/nfts-me-bg.png',
    bgGradientColor: '#010101',
    tags: ['NFT'],
    href: 'https://nfts2me.com/app/push-testnet/',
    titleColor: '#FFFFFF',
    secondary: true,
  },
  {
    nameKey: 'components.ecosystem-apps-partners.apps.tachyon.name',
    descriptionKey:
      'components.ecosystem-apps-partners.apps.tachyon.description',
    icon: '/assets/ecosystem/tachyon-icon.png',
    bgImage: '/assets/ecosystem/tachyon-bg.png',
    bgGradientColor: '#0536A0',
    tags: ['Infra'],
    href: 'https://docs.rath.fi/',
    titleColor: 'white',
    secondary: true,
  },
];
