export const FeaturesList = {
  meta: {
    title: 'pages.home.chain-features-section.header.main-text',
    subtitle: 'pages.home.chain-features-section.header.other-text',
    footer: {
      title: 'pages.home.chain-features-section.footer.title',
      secondary: 'pages.home.chain-features-section.footer.secondary',
      ctaText: 'pages.home.chain-features-section.footer.ctatext',
      ctaTitle: 'pages.home.chain-features-section.footer.ctatitle',
    },
  },
  first: [
    {
      config: {
        id: 'any-chain',
        padding: '32px',
        containerFlexDirection: 'column-reverse',
        height: '490px',
        fluid: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'image',
          imagesrc: 'chain/any-chain',
          // lottiesrc: 'chain/any-chain-lottie',
          videosrc: 'chain/any-chain-video',
          videowebm: true,
          imagealt: 'pages.home.chain-features-section.box1.imagealt',
          imagetitle: 'pages.home.chain-features-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: '0 0 auto 0',
        },
        {
          type: 'text',
          texttitle: 'pages.home.chain-features-section.box1.texttitle',
          bodytext: 'pages.home.chain-features-section.box1.bodytext',
          bodytextcolor: 'var(--ifm-color-features-gradient)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
      ],
    },
    {
      config: {
        id: 'wallet-abstraction',
        padding: '32px',
        height: '490px',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'text',
          texttitle: 'pages.home.chain-features-section.box2.texttitle',
          bodytext: 'pages.home.chain-features-section.box2.bodytext',
          bodytextcolor: 'var(--ifm-color-features-gradient)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'image',
          imagesrc: 'chain/wallet-abstraction',
          videosrc: 'chain/wallet-abstraction-video',
          videowebm: true,
          imagealt: 'pages.home.chain-features-section.box2.imagealt',
          imagetitle: 'pages.home.chain-features-section.box2.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: 'auto 0 0 0',
        },
      ],
    },
  ],
  second: [
    {
      config: {
        id: 'evm-compatible',
        containerFlexDirection: 'column-reverse',
        height: '490px',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'image',
          imagesrc: 'chain/evm-compatible',
          videosrc: 'chain/evm-compatible-video',
          videowebm: true,
          imagealt: 'pages.home.chain-features-section.box3.imagealt',
          imagetitle: 'pages.home.chain-features-section.box3.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: 'auto 0 0 0',
        },
        {
          type: 'text',
          texttitle: 'pages.home.chain-features-section.box3.texttitle',
          bodytext: 'pages.home.chain-features-section.box3.bodytext',
          bodytextcolor: 'var(--ifm-color-features-gradient)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
      ],
    },
    {
      config: {
        id: 'universal-smart-contract',
        height: '490px',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'text',
          texttitle: 'pages.home.chain-features-section.box4.texttitle',
          bodytext: 'pages.home.chain-features-section.box4.bodytext',
          bodytextcolor: 'var(--ifm-color-features-gradient)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'image',
          imagesrc: 'chain/universal-smart-contract',
          videosrc: 'chain/universal-smart-contract-video',
          videowebm: true,
          imagealt: 'pages.home.chain-features-section.box4.imagealt',
          imagetitle: 'pages.home.chain-features-section.box4.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: '0 0 auto 0',
        },
      ],
    },
    {
      config: {
        id: 'universal-fee',
        containerFlexDirection: 'column-reverse',
        fluid: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        height: '490px',
        hide: {
          desktop: false,
          laptop: true,
          tablet: true,
          mobile: true,
        },
      },
      body: [
        {
          type: 'text',
          texttitle: 'pages.home.chain-features-section.box5.texttitle',
          bodytext: 'pages.home.chain-features-section.box5.bodytext',
          bodytextcolor: 'var(--ifm-color-features-gradient)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'image',
          imagesrc: 'chain/universal-fee',
          videosrc: 'chain/universal-fee-video',
          videowebm: true,
          imagealt: 'pages.home.chain-features-section.box5.imagealt',
          imagetitle: 'pages.home.chain-features-section.box5.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: 'auto 0 0 0',
        },
      ],
    },
  ],
  third: [
    {
      config: {
        id: 'universal-execution-layer',
        height: '490px',
        containerFlexDirection: 'column-reverse',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'image',
          imagesrc: 'chain/universal-execution-layer',
          videosrc: 'chain/universal-execution-layer-video',
          videowebm: true,
          imagealt: 'pages.home.chain-features-section.box6.imagealt',
          imagetitle: 'pages.home.chain-features-section.box6.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: '0 0 auto 0',
        },
        {
          type: 'text',
          texttitle: 'pages.home.chain-features-section.box6.texttitle',
          bodytext: 'pages.home.chain-features-section.box6.bodytext',
          bodytextcolor: 'var(--ifm-color-features-gradient)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
      ],
    },
    {
      config: {
        id: 'universal-fee-alt',
        containerFlexDirection: 'column-reverse',
        fluid: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        height: '490px',
        hide: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'text',
          texttitle: 'pages.home.chain-features-section.box5.texttitle',
          bodytext: 'pages.home.chain-features-section.box5.bodytext',
          bodytextcolor: 'var(--ifm-color-features-gradient)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'image',
          imagesrc: 'chain/universal-fee',
          videosrc: 'chain/universal-fee-video',
          videowebm: true,
          imagealt: 'pages.home.chain-features-section.box5.imagealt',
          imagetitle: 'pages.home.chain-features-section.box5.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: 'auto 0 0 0',
        },
      ],
    },
    {
      config: {
        id: 'shared-state',
        height: '490px',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: true,
          tablet: true,
          mobile: true,
        },
      },
      body: [
        {
          type: 'text',
          tags: [
            {
              title: 'pages.home.chain-features-section.box7.tags.title1',
              background: 'transparent',
              color: 'var(--ifm-color-pink-100)',
              border: '1px solid var(--ifm-color-pink-100)',
              fontSize: '9px',
            },
          ],
          texttitle: 'pages.home.chain-features-section.box7.texttitle',
          bodytext: 'pages.home.chain-features-section.box7.bodytext',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'image',
          imagesrc: 'chain/programmable-solvers',
          videosrc: 'chain/programmable-solvers-video',
          videowebm: true,
          imagealt: 'pages.home.chain-features-section.box7.imagealt',
          imagetitle: 'pages.home.chain-features-section.box7.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: 'auto 0 0 0',
        },
      ],
    },
    {
      config: {
        id: 'programmable-solvers',
        containerFlexDirection: 'column-reverse',
        height: '490px',
        fluid: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: true,
          tablet: true,
          mobile: true,
        },
      },
      body: [
        {
          type: 'image',
          imagesrc: 'chain/shared-state',
          videosrc: 'chain/shared-state-video',
          videowebm: true,
          imagealt: 'pages.home.chain-features-section.box8.imagealt',
          imagetitle: 'pages.home.chain-features-section.box8.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: '0 0 auto 0',
        },
        {
          type: 'text',
          tagText: 'pages.home.chain-features-section.box8.tagText',
          tags: [
            {
              title: 'pages.home.chain-features-section.box8.tags.title1',
              background: 'transparent',
              color: 'var(--ifm-color-pink-100)',
              border: '1px solid var(--ifm-color-pink-100)',
              fontSize: '9px',
            },
          ],
          texttitle: 'pages.home.chain-features-section.box8.texttitle',
          bodytext: 'pages.home.chain-features-section.box8.bodytext',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
      ],
    },
  ],
};
