export const InvList = {
  top: [
    {
      srcref: 'jump',
      id: 'jump',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Jump',
    },
    {
      srcref: 'parafi',
      id: 'parafi',
      title: null,
      subtitle: null,
      alt: 'Push Investor - ParaFi',
    },
    {
      srcref: 'vcAndrew',
      id: 'andrew',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Andrew Keys',
    },
    {
      srcref: 'true',
      id: 'true',
      title: null,
      subtitle: null,
      alt: 'Push Investor - True',
    },
    {
      srcref: 'iosg',
      id: 'iosg',
      title: null,
      subtitle: null,
      alt: 'Push Investor - IOSG',
    },
    {
      srcref: '4rc',
      id: '4rc',
      title: null,
      subtitle: null,
      alt: 'Push Investor - 4RC',
    },
    {
      srcref: 'vcSandeep',
      id: 'sandeep',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Sandeep',
    },
    {
      srcref: 'aCapital',
      id: 'a_capital',
      title: null,
      subtitle: null,
      alt: 'Push Investor - A Capital',
    },
    {
      srcref: 'thelao',
      id: 'thelao',
      title: null,
      subtitle: null,
      alt: 'Push Investor - The LAO',
    },
    {
      srcref: 'vcKenneth',
      id: 'kenneth',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Kenneth Ng',
    },
  ],
  bottom: [
    {
      srcref: 'tigerglobal',
      id: 'tigerglobal',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Tiger Global',
    },
    {
      srcref: 'vcDefi-dad',
      id: 'defi-dad',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Defi dad',
    },
    {
      srcref: 'binance',
      id: 'binancelabs',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Binance Labs',
    },
    {
      srcref: 'vcBalaji',
      id: 'balaji',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Balaji Srinivasan',
    },
    {
      srcref: 'polygon-studios',
      id: 'polygonstudios',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Polygon Studios',
    },
    {
      srcref: 'sino',
      id: 'sino',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Sino Global Capital',
    },
    {
      srcref: 'vcAnton',
      id: 'anton',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Anton Bukov',
    },
    {
      srcref: 'zee-prime',
      id: 'zee-prime',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Zee Prime',
    },
    {
      srcref: 'signum',
      id: 'signum',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Signum Capital',
    },
    {
      srcref: 'vcScott',
      id: 'scott',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Scott Moore',
    },
  ],
};
