export const NotifFeaturesList = {
  first: [
    {
      config: {
        id: 'any-chain',
        padding: '32px',
        containerFlexDirection: 'column-reverse',
        height: '490px',
        fluid: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'image',
          imagesrc: 'chain/any-chain',
          lottiesrc: 'chain/any-chain-lottie',
          imagealt: 'home.notification-section.box1.imagealt',
          imagetitle: 'home.notification-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: '0 0 auto 0',
        },
        {
          type: 'text',
          texttitle: 'Any Chain Transactions',
          bodytext:
            'Push Chain supports transactions from any blockchain. Users can pay gas in any token — No need for bridging.',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
      ],
    },
    {
      config: {
        id: 'wallet-abstraction',
        padding: '32px',
        height: '490px',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'text',
          texttitle: 'Wallet Abstraction',
          bodytext:
            'Let any wallet from any chain connect, interact, and transact. Break web3 barriers by using social login or email. User get to decide on Push Chain.',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'styled-link',
          href: 'https://example.com/learn-more',
          hrefText: 'Learn More',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'image',
          imagesrc: 'chain/wallet-abstraction',
          videosrc: 'chain/wallet-abstraction-video',
          videowebm: true,
          imagealt: 'home.notification-section.box1.imagealt',
          imagetitle: 'home.notification-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: 'auto 0 0 0',
        },
      ],
    },
  ],
  second: [
    {
      config: {
        id: 'evm-compatible',
        containerFlexDirection: 'column-reverse',
        height: '490px',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'image',
          imagesrc: 'chain/evm-compatible',
          // videosrc: 'chain/evm-compatible',
          // videowebm: true,
          imagealt: 'home.notification-section.box1.imagealt',
          imagetitle: 'home.notification-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: 'auto 0 0 0',
        },
        {
          type: 'text',
          texttitle: '100% EVM\nCompatible',
          bodytext:
            'Deploy with zero on-chain code. Turn your native app into a universal app in minutes.',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
      ],
    },
    {
      config: {
        id: 'universal-smart-contract',
        height: '490px',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'text',
          texttitle: 'Universal Smart Contracts',
          bodytext:
            'Build once, run cross chain, multi step experiences  with a single, future-proof contract.',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'image',
          imagesrc: 'chain/universal-smart-contract',
          // videosrc: 'chain/wallet-abstraction-video',
          // videowebm: true,
          imagealt: 'home.notification-section.box1.imagealt',
          imagetitle: 'home.notification-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: '0 0 auto 0',
        },
      ],
    },
    {
      config: {
        id: 'universal-fee',
        containerFlexDirection: 'column-reverse',
        fluid: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        height: '490px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: true,
        },
      },
      body: [
        {
          type: 'text',
          texttitle: 'Universal Fee\nAbstraction',
          bodytext:
            'Let’s users pay gas in any token, on any chain without bridging.',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'image',
          imagesrc: 'chain/universal-fee',
          // videosrc: 'chain/wallet-abstraction-video',
          // videowebm: true,
          imagealt: 'home.notification-section.box1.imagealt',
          imagetitle: 'home.notification-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: 'auto 0 0 0',
        },
      ],
    },
  ],
  third: [
    {
      config: {
        id: 'universal-execution-layer',
        height: '490px',
        containerFlexDirection: 'column-reverse',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'image',
          imagesrc: 'chain/universal-execution-layer',
          // videosrc: 'chain/evm-compatible',
          // videowebm: true,
          imagealt: 'home.notification-section.box1.imagealt',
          imagetitle: 'home.notification-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: '0 0 auto 0',
        },
        {
          type: 'text',
          texttitle: 'Universal Execution Layer',
          bodytext:
            'Build atomic, composable apps across web3. Create never seen before app experiences, by having multiple users of different chains transact with the same app.',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
      ],
    },
    {
      config: {
        id: 'shared-state',
        height: '490px',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'text',
          texttitle: 'Shared State',
          bodytext:
            'Access account and state data from other chains in your smart contract.',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'image',
          imagesrc: 'chain/shared-state',
          // videosrc: 'chain/wallet-abstraction-video',
          // videowebm: true,
          imagealt: 'home.notification-section.box1.imagealt',
          imagetitle: 'home.notification-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: 'auto 0 0 0',
        },
      ],
    },
    {
      config: {
        id: 'programmable-solvers',
        containerFlexDirection: 'column-reverse',
        height: '490px',
        fluid: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: true,
        },
      },
      body: [
        {
          type: 'image',
          imagesrc: 'chain/programmable-solvers',
          // videosrc: 'chain/wallet-abstraction-video',
          // videowebm: true,
          imagealt: 'home.notification-section.box1.imagealt',
          imagetitle: 'home.notification-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: '0 0 auto 0',
        },
        {
          type: 'text',
          texttitle: 'Programmable\nSolvers',
          bodytext:
            'Trigger, validate, and complete transactions across any chain using your smart contract.',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
      ],
    },
  ],
  tabletOnly: [
    {
      config: {
        id: 'universal-fee',
        containerFlexDirection: 'column-reverse',
        height: '490px',
        fluid: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: true,
        },
      },
      header: {
        title: 'Universal Fee\nAbstraction',
        align: 'left',
      },
      mockimage: true,
      body: [
        {
          type: 'text',
          texttitle: 'Universal Fee\nAbstraction',
          bodytext:
            'Let’s users pay gas in any token, on any chain without bridging.',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
        {
          type: 'image',
          imagesrc: 'chain/universal-fee',
          // videosrc: 'chain/wallet-abstraction-video',
          // videowebm: true,
          imagealt: 'home.notification-section.box1.imagealt',
          imagetitle: 'home.notification-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: 'auto 0 0 0',
        },
      ],
    },
    {
      config: {
        id: 'lightweight',
        height: '490px',
        fluid: {
          desktop: true,
          laptop: false,
          tablet: false,
          mobile: false,
        },
        padding: '32px',
        hide: {
          desktop: false,
          laptop: false,
          tablet: false,
          mobile: false,
        },
      },
      body: [
        {
          type: 'image',
          imagesrc: 'chain/universal-execution-layer',
          // videosrc: 'chain/evm-compatible',
          // videowebm: true,
          imagealt: 'home.notification-section.box1.imagealt',
          imagetitle: 'home.notification-section.box1.imagetitle',
          imagewidth: 'auto',
          imageheight: 'auto',
          imagemargin: '0 0 auto 0',
        },
        {
          type: 'text',
          texttitle: 'Universal Execution Layer',
          bodytext:
            'Build atomic, composable apps across web3. Create never seen before app experiences, by having multiple users of different chains transact with the same app.',
          bodytextcolor: 'linear-gradient(90deg, #B1B1B9 0%, #635D65 100%)',
          bodytextsize: '1.125rem',
          bodytextweight: '400',
          margin: '0px 0 0 0',
          align: 'left',
        },
      ],
    },
  ],
};
