export const SupportedLanguagesList = [
  {
    language: 'English',
    srcref: 'en',
    id: 'en',
    ctatitle: 'header.language.english-ctatitle',
    ctatext: 'header.language.english',
  },
  {
    language: 'Chinese Simplified',
    srcref: 'zh-CN',
    id: 'zh-CN',
    ctatitle: 'header.language.chinese_simplified-ctatitle',
    ctatext: 'header.language.chinese_simplified',
  },
  {
    language: 'Spanish',
    srcref: 'es',
    id: 'es',
    ctatitle: 'header.language.spanish-ctatitle',
    ctatext: 'header.language.spanish',
  },
  {
    language: 'Hindi',
    srcref: 'hi',
    id: 'hi',
    ctatitle: 'header.language.hindi-ctatitle',
    ctatext: 'header.language.hindi',
  },
  {
    language: 'Japanese',
    srcref: 'ja',
    id: 'ja',
    ctatitle: 'header.language.japanese-ctatitle',
    ctatext: 'header.language.japanese',
  },
  {
    language: 'Korean',
    srcref: 'ko',
    id: 'ko',
    ctatitle: 'header.language.korean-ctatitle',
    ctatext: 'header.language.korean',
  },
  {
    language: 'Portuguese',
    srcref: 'pt',
    id: 'pt',
    ctatitle: 'header.language.portuguese-ctatitle',
    ctatext: 'header.language.portuguese',
  },
  {
    language: 'Russian',
    srcref: 'ru',
    id: 'ru',
    ctatitle: 'header.language.russian-ctatitle',
    ctatext: 'header.language.russian',
  },
  {
    language: 'Turkish',
    srcref: 'tr',
    id: 'tr',
    ctatitle: 'header.language.turkish-ctatitle',
    ctatext: 'header.language.turkish',
  },
  {
    language: 'French',
    srcref: 'fr',
    id: 'fr',
    ctatitle: 'header.language.french-ctatitle',
    ctatext: 'header.language.french',
  },
  {
    language: 'Indonesian',
    srcref: 'id',
    id: 'id',
    ctatitle: 'header.language.indonesian-ctatitle',
    ctatext: 'header.language.indonesian',
  },
  {
    language: 'Vietnamese',
    srcref: 'vi',
    id: 'vi',
    ctatitle: 'header.language.vietnamese-ctatitle',
    ctatext: 'header.language.vietnamese',
  },
  {
    language: 'German',
    srcref: 'de',
    id: 'de',
    ctatitle: 'header.language.german-ctatitle',
    ctatext: 'header.language.german',
  },
  {
    language: 'Arabic',
    srcref: 'ar',
    id: 'ar',
    ctatitle: 'header.language.arabic-ctatitle',
    ctatext: 'header.language.arabic',
  },
];
