name: Deploy PR previews
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: |
          echo "REACT_APP_PREVIEW_BASE=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "REACT_APP_DEPLOY_ENV=PREVIEW" >> $GITHUB_ENV
          echo "REACT_APP_PUBLIC_URL=https://pushchain.github.io" >> $GITHUB_ENV
          echo "GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "REACT_APP_BASE_URL=/push-chain-website/pr-preview/pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "WINDSURF_API_KEY=${{ secrets.WINDSURF_API_KEY }}" >> $GITHUB_ENV

      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v4

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.2.2 --activate

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - run: yarn install
      - run: yarn build:pr:preview

      - uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: ./build/
          umbrella-dir: pr-preview
